import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StoreProvider from './store/StoreProvider'
import Header from './components/Header'
import Footer from './components/Footer'
import { getPeopleDetails } from './api/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const signedUser = await getPeopleDetails()

  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider signedUser={signedUser}>
          <Header />
            {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  )
}
